config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'groups/index'
      post 'groups/create'
      delete 'groups/:id', to: 'groups#destroy'
    end
  end
  
  root "groups#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all.order(year: :desc)
    render json: @groups
  end

  # GET /groups/1 or /groups/1.json
  def show
    if @group
      render json: @group
    else
      render json: @group.errors
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    if @group.save
      render json: @group
    else
      render json: @group.errors
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    render json: { notice: "Group was successfully destroyed." }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :style, :author, :year, :coac_position, :image_url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # This controller’s only function is to provide a direct route from Rails to React, 
  # which is why we’re only setting the index method.
  # You’ll also need to empty the index.html.erb file within the app/views/ folder 
  # we don’t want any of the Rails web content to be rendered. 
  # It’s a trick we can use to force Rails to exhibit React code only.
  def index; end
end

app/helpers/api/v1/groups_helper.rb
module Api::V1::GroupsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :coac_position %>
    <%= form.number_field :coac_position %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Style:</strong>
  <%= @group.style %>
</p>

<p>
  <strong>Author:</strong>
  <%= @group.author %>
</p>

<p>
  <strong>Year:</strong>
  <%= @group.year %>
</p>

<p>
  <strong>Coac position:</strong>
  <%= @group.coac_position %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @group.image_url %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- 
      This will add the JavaScript pack to our application header, which will cause all the JavaScript files, including React ones, to be executed within the index page.
     -->
    <%= javascript_pack_tag 'index' %>
    
    <title>ReactOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>